In [9]:
from math import *

In [10]:
sqrt

<function math.sqrt(x, /)>

In [3]:
import numpy as np

def vec(*components):
    return np.array(components).reshape(len(components), 1)


In [20]:
u = vec(1, 1)
v = vec(4, 5)

In [21]:
u

array([[1],
       [1]])

In [22]:
v

array([[4],
       [5]])

In [23]:
u + v

array([[5],
       [6]])

In [24]:
u - v

array([[-3],
       [-4]])

In [29]:
def length(a):
    return sqrt( a[0]**2 + a[1]**2 )

In [35]:
length( vec(3, 4) )

5.0

In [30]:
length(u - v)

5.0

In [25]:
def distance(a, b):
    return sqrt( (b[1] - a[1]) ** 2 + (b[0] - a[0]) ** 2 )

In [26]:
distance(u, v)

5.0

In [36]:
def unit(a):
    return a / length(a)

In [51]:
def dot(a, b):
    return a[0] * b[0] + a[1] * b[1]

In [52]:
def angle(a, b):
    return np.degrees(   np.arccos( dot(unit(a), unit(b)) ) )

In [53]:
angle(vec(1, 1), vec(1, 0))

array([45.])

In [54]:
i = vec(1, 0)
j = vec(0, 1)

In [56]:
v

array([[4],
       [5]])

In [57]:
4*i + 5*j

array([[4],
       [5]])

In [59]:
all(4*i + 5*j == v) # all components equal

True

In [68]:
def matrix(*col_vectors):
    return np.column_stack(col_vectors)

In [60]:
matrix(u, v)

array([[1, 4],
       [1, 5]])

In [62]:
matrix(u, v) @ i

array([[1],
       [1]])

In [63]:
matrix(u, v) @ j

array([[4],
       [5]])

In [65]:
all(  matrix(u, v) @ i == u )

True

In [67]:
all(  matrix(u, v) @ j == v )

True

In [69]:
def identity(size):
    return np.eye(size)

In [74]:
identity(2)

array([[1., 0.],
       [0., 1.]])

In [75]:
matrix(u, v) @ identity(2)

array([[1., 4.],
       [1., 5.]])

In [87]:
def rotation(angle):
    angle = np.radians(angle)
    
    new_i = vec(np.cos(angle), np.sin(angle))
    new_j = vec(-np.sin(angle), np.cos(angle))
    
    return matrix(new_i, new_j).round(3)

In [92]:
rotation(90) @ matrix(u, v)

array([[-1., -5.],
       [ 1.,  4.]])

In [89]:
rotation(+90) @ identity(2)

array([[ 0., -1.],
       [ 1.,  0.]])

In [91]:
rotation(-90) @ identity(2)

array([[ 0.,  1.],
       [-1.,  0.]])

In [93]:
def inverse(m):
    from numpy.linalg import inv
    return inv(m)

In [94]:
inverse(rotation(-90))

array([[-0., -1.],
       [ 1.,  0.]])

In [95]:
inverse(rotation(-90)) @ rotation(-90)

array([[1., 0.],
       [0., 1.]])

In [96]:
matrix(u, v) @ inverse(rotation(-90)) @ rotation(-90)

array([[1., 4.],
       [1., 5.]])

## Part 2

In [107]:
def unit_circle_sample(n):
    radians = np.linspace(0, 2*np.pi, n)

    circle_x = np.cos(radians)
    circle_y = np.sin(radians)

    return [ vec(x, y) for x, y in zip(circle_x, circle_y) ]

unit_circle_sample(3)

[array([[1.],
        [0.]]), array([[-1.0000000e+00],
        [ 1.2246468e-16]]), array([[ 1.0000000e+00],
        [-2.4492936e-16]])]

In [110]:
all([round(length(r)) == 1 for r in unit_circle_sample(40)])

True

In [98]:

for e in np.c_[np.cos(1), np.sin(1)]:
    print(e)

[0.54030231 0.84147098]


In [105]:
np.hstack([np.cos(1), np.sin(0)])

array([0.54030231, 0.        ])